name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Update version if manually triggered
      if: github.event_name == 'workflow_dispatch'
      run: |
        # Update version in setup.py
        sed -i "s/version=\"[0-9]\+\.[0-9]\+\.[0-9]\+\"/version=\"${{ github.event.inputs.version }}\"/g" setup.py
        # Commit the version change
        git config --local user.email "abedinia.aydin@gmail.com"
        git config --local user.name "Aydin Abedinia"
        git add setup.py
        git commit -m "Bump version to ${{ github.event.inputs.version }}"
        git tag -a v${{ github.event.inputs.version }} -m "Version ${{ github.event.inputs.version }}"
        git push --tags
    - name: Build package
      run: |
        python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        skip_existing: true
